export { default } from "./DashboardPage";
export { default as DashboardPage } from "./DashboardPage";
export { default as AwardRepPage } from "./pages/AwardRepPage";
export { default as RevokeRepPage } from "./pages/RevokeRepPage";
export { default as ManageAwardersPage } from "./pages/ManageAwardersPage";
export { default as ViewBalancesPage } from "./pages/ViewBalancesPage";
export { default as TransactionLogPage } from "./pages/TransactionLogPage";
export { default as DecaySystemPage } from "./pages/DecaySystemPage";
export { default as SettingsAdminPage } from "./pages/SettingsPage";
export { default as EconomySettingsPage } from "./pages/EconomySettingsPage";
export { default as MyEarningsPage } from "./pages/MyEarningsPage";
